#include "sci.h"
#include "util.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* GraalVM isolate headers (generated by native-image --shared) */
#include "graal_isolate.h"
#include "libsci.h"

/* GraalVM isolate handles (single-threaded: one isolate, one thread) */
static graal_isolate_t *isolate = NULL;
static graal_isolatethread_t *thread = NULL;

bool sci_init(void) {
    if (graal_create_isolate(NULL, &isolate, &thread) != 0) {
        fprintf(stderr, "Failed to create GraalVM isolate\n");
        return false;
    }

    int rc = libsci_init(thread);
    if (rc != 0) {
        fprintf(stderr, "sci_init failed\n");
        graal_tear_down_isolate(thread);
        isolate = NULL;
        thread = NULL;
        return false;
    }

    return true;
}

void sci_shutdown(void) {
    if (thread) {
        libsci_shutdown(thread);
        graal_tear_down_isolate(thread);
        thread = NULL;
        isolate = NULL;
    }
}

bool sci_is_ready(void) {
    return thread != NULL;
}

char *sci_eval(const char *expr) {
    if (!thread) return hstrdup("ERROR: SCI not initialized");

    char *result = libsci_eval_string(thread, (char *)expr);
    if (!result) return hstrdup("nil");

    /* Copy the result so caller can free() it normally.
     * GraalVM strings have their own lifecycle. */
    char *copy = hstrdup(result);
    libsci_free_string(thread, result);
    return copy;
}

long long sci_get_state_version(void) {
    if (!thread) return -1;
    return libsci_get_state_version(thread);
}

char *sci_load_file(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) {
        char err[256];
        snprintf(err, sizeof(err), "ERROR: Could not open %s", path);
        return hstrdup(err);
    }

    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);

    char *content = malloc(len + 1);
    if (!content) {
        fclose(f);
        return hstrdup("ERROR: Out of memory");
    }

    size_t read = fread(content, 1, len, f);
    content[read] = '\0';
    fclose(f);

    char *result = sci_eval(content);
    free(content);
    return result;
}

/* ================================================================
 * Sexp utilities (moved from clojure.c, pure C string parsing)
 * ================================================================ */

bool clojure_is_symbol_char(char ch) {
    if (isalnum(ch)) return true;
    return ch == '-' || ch == '_' || ch == '.' || ch == '/' ||
           ch == '+' || ch == '*' || ch == '!' || ch == '?' ||
           ch == '<' || ch == '>' || ch == '=' || ch == '&' ||
           ch == '%' || ch == '#' || ch == ':' || ch == '\'';
}

static size_t find_matching_open(const char *text, size_t pos, char open, char close) {
    int depth = 1;
    while (pos > 0) {
        pos--;
        char ch = text[pos];

        if (ch == '"') {
            pos--;
            while (pos > 0 && text[pos] != '"') {
                if (text[pos] == '\\' && pos > 0) pos--;
                pos--;
            }
            continue;
        }

        if (ch == close) depth++;
        else if (ch == open) {
            depth--;
            if (depth == 0) return pos;
        }
    }
    return (size_t)-1;
}

size_t clojure_find_sexp_start(const char *text, size_t pos) {
    if (pos == 0) return (size_t)-1;

    while (pos > 0 && (text[pos - 1] == ' ' || text[pos - 1] == '\n' || text[pos - 1] == '\t'))
        pos--;

    if (pos == 0) return (size_t)-1;

    char ch = text[pos - 1];

    if (ch == ')') {
        size_t start = find_matching_open(text, pos - 1, '(', ')');
        if (start == (size_t)-1) return (size_t)-1;
        while (start > 0 && (text[start - 1] == '#' || text[start - 1] == '\'' ||
                             text[start - 1] == '`' || text[start - 1] == '~' ||
                             text[start - 1] == '@'))
            start--;
        return start;
    }

    if (ch == ']') {
        size_t start = find_matching_open(text, pos - 1, '[', ']');
        if (start == (size_t)-1) return (size_t)-1;
        return start;
    }

    if (ch == '}') {
        size_t start = find_matching_open(text, pos - 1, '{', '}');
        if (start == (size_t)-1) return (size_t)-1;
        if (start > 0 && text[start - 1] == '#')
            start--;
        return start;
    }

    if (ch == '"') {
        size_t p = pos - 2;
        while (p > 0) {
            if (text[p] == '"') {
                int backslashes = 0;
                size_t bp = p;
                while (bp > 0 && text[bp - 1] == '\\') {
                    backslashes++;
                    bp--;
                }
                if (backslashes % 2 == 0)
                    return p;
            }
            p--;
        }
        if (text[0] == '"') return 0;
        return (size_t)-1;
    }

    if (clojure_is_symbol_char(ch) || isdigit(ch)) {
        size_t start = pos - 1;
        while (start > 0 && clojure_is_symbol_char(text[start - 1]))
            start--;
        if (start > 0 && text[start - 1] == '@')
            start--;
        return start;
    }

    return (size_t)-1;
}

char *clojure_extract_sexp(const char *text, size_t pos) {
    size_t start = clojure_find_sexp_start(text, pos);
    if (start == (size_t)-1) return NULL;

    while (pos > 0 && (text[pos - 1] == ' ' || text[pos - 1] == '\n' || text[pos - 1] == '\t'))
        pos--;

    size_t len = pos - start;
    return hstrndup(text + start, len);
}
