#include "sci.h"
#include "util.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>
#include <errno.h>

/* GraalVM isolate headers (generated by native-image --shared) */
#include "graal_isolate.h"
#include "libsci.h"

/* GraalVM isolate handles (single-threaded: one isolate, one thread) */
static graal_isolate_t *isolate = NULL;
static graal_isolatethread_t *thread = NULL;

bool sci_init(void) {
    if (graal_create_isolate(NULL, &isolate, &thread) != 0) {
        fprintf(stderr, "Failed to create GraalVM isolate\n");
        return false;
    }

    int rc = libsci_init(thread);
    if (rc != 0) {
        fprintf(stderr, "sci_init failed\n");
        graal_tear_down_isolate(thread);
        isolate = NULL;
        thread = NULL;
        return false;
    }

    return true;
}

void sci_shutdown(void) {
    if (thread) {
        libsci_shutdown(thread);
        graal_tear_down_isolate(thread);
        thread = NULL;
        isolate = NULL;
    }
}

bool sci_is_ready(void) {
    return thread != NULL;
}

char *sci_eval(const char *expr) {
    if (!thread) return hstrdup("ERROR: SCI not initialized");

    char *result = libsci_eval_string(thread, (char *)expr);
    if (!result) return hstrdup("nil");

    /* Copy the result so caller can free() it normally.
     * GraalVM strings have their own lifecycle. */
    char *copy = hstrdup(result);
    libsci_free_string(thread, result);
    return copy;
}

/* Read all available bytes from fd into a malloc'd, NUL-terminated string.
 * Returns NULL on error. */
static char *read_all(int fd) {
    size_t cap = 4096, len = 0;
    char *buf = malloc(cap);
    if (!buf) return NULL;
    for (;;) {
        if (len + 1 >= cap) {
            cap *= 2;
            char *nb = realloc(buf, cap);
            if (!nb) { free(buf); return NULL; }
            buf = nb;
        }
        ssize_t r = read(fd, buf + len, cap - len - 1);
        if (r > 0) { len += (size_t)r; continue; }
        if (r == 0) break;                /* EOF */
        if (errno == EINTR) continue;
        if (errno == EAGAIN || errno == EWOULDBLOCK) break;
        free(buf);
        return NULL;
    }
    buf[len] = '\0';
    return buf;
}

SciEvalResult sci_eval_interruptible(const char *expr) {
    SciEvalResult out = { NULL, false };

    if (!thread) {
        out.result = hstrdup("ERROR: SCI not initialized");
        return out;
    }

    int pipefd[2];
    if (pipe(pipefd) != 0) {
        /* Fall back to synchronous eval if pipe creation fails. */
        out.result = sci_eval(expr);
        return out;
    }

    pid_t pid = fork();
    if (pid < 0) {
        /* Fork failed — fall back to synchronous eval. */
        close(pipefd[0]);
        close(pipefd[1]);
        out.result = sci_eval(expr);
        return out;
    }

    if (pid == 0) {
        /* ---- Child ----
         * Evaluate, write result to the pipe, exit. Do NOT touch ncurses,
         * stdin, or any shared filesystem state. The CoW copy of the SCI
         * isolate is used only by this child and discarded on _exit. */
        close(pipefd[0]);

        /* Redirect stdin/stdout/stderr to /dev/null so any libsci debug
         * output or accidental terminal writes from the child can't corrupt
         * the parent's ncurses display. */
        int devnull = open("/dev/null", O_RDWR);
        if (devnull >= 0) {
            dup2(devnull, STDIN_FILENO);
            dup2(devnull, STDOUT_FILENO);
            dup2(devnull, STDERR_FILENO);
            if (devnull > STDERR_FILENO) close(devnull);
        }

        char *result = libsci_eval_string(thread, (char *)expr);
        const char *out_str = result ? result : "nil";
        size_t rlen = strlen(out_str);

        /* Write in a loop to handle partial writes on large results. */
        size_t written = 0;
        while (written < rlen) {
            ssize_t w = write(pipefd[1], out_str + written, rlen - written);
            if (w < 0) {
                if (errno == EINTR) continue;
                break;
            }
            written += (size_t)w;
        }
        close(pipefd[1]);
        _exit(0);
    }

    /* ---- Parent ---- */
    close(pipefd[1]);
    /* Non-blocking so read_all doesn't hang if fewer bytes than expected. */
    int flags = fcntl(pipefd[0], F_GETFL, 0);
    if (flags != -1) fcntl(pipefd[0], F_SETFL, flags | O_NONBLOCK);

    bool done = false;
    while (!done) {
        struct pollfd fds[2];
        fds[0].fd = pipefd[0]; fds[0].events = POLLIN; fds[0].revents = 0;
        fds[1].fd = STDIN_FILENO; fds[1].events = POLLIN; fds[1].revents = 0;

        int pr = poll(fds, 2, 100);  /* 100ms tick for spinner updates */
        if (pr < 0) {
            if (errno == EINTR) continue;
            break;
        }

        /* Check stdin first so C-g wins over a just-arrived result. */
        if (fds[1].revents & POLLIN) {
            unsigned char buf[64];
            ssize_t n = read(STDIN_FILENO, buf, sizeof(buf));
            if (n > 0) {
                bool quit = false;
                for (ssize_t i = 0; i < n; i++) {
                    if (buf[i] == 7 /* C-g */ || buf[i] == 27 /* ESC */) {
                        quit = true; break;
                    }
                }
                if (quit) {
                    kill(pid, SIGKILL);
                    waitpid(pid, NULL, 0);
                    close(pipefd[0]);
                    out.cancelled = true;
                    return out;
                }
                /* Non-quit bytes are swallowed — acceptable since the user
                 * is being told "Evaluating... (C-g to cancel)". */
            }
        }

        if (fds[0].revents & (POLLIN | POLLHUP)) {
            /* Drain pipe — child may have exited, so read to EOF. */
            char *data = read_all(pipefd[0]);
            if (data && data[0] != '\0') {
                out.result = data;   /* already NUL-terminated */
            } else {
                /* Empty result usually means the child crashed before it
                 * could write anything. Surface that as an error so the
                 * user doesn't silently see "nil". */
                free(data);
                out.result = hstrdup("sci_eval error: child process died "
                                     "before producing a result");
            }
            done = true;
        }
    }

    close(pipefd[0]);
    waitpid(pid, NULL, 0);
    if (!out.result) out.result = hstrdup("nil");
    return out;
}

long long sci_get_state_version(void) {
    if (!thread) return -1;
    return libsci_get_state_version(thread);
}

char *sci_load_file(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) {
        char err[256];
        snprintf(err, sizeof(err), "ERROR: Could not open %s", path);
        return hstrdup(err);
    }

    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);

    char *content = malloc(len + 1);
    if (!content) {
        fclose(f);
        return hstrdup("ERROR: Out of memory");
    }

    size_t read = fread(content, 1, len, f);
    content[read] = '\0';
    fclose(f);

    char *result = sci_eval(content);
    free(content);
    return result;
}

/* ================================================================
 * Sexp utilities (moved from clojure.c, pure C string parsing)
 * ================================================================ */

bool clojure_is_symbol_char(char ch) {
    if (isalnum(ch)) return true;
    return ch == '-' || ch == '_' || ch == '.' || ch == '/' ||
           ch == '+' || ch == '*' || ch == '!' || ch == '?' ||
           ch == '<' || ch == '>' || ch == '=' || ch == '&' ||
           ch == '%' || ch == '#' || ch == ':' || ch == '\'';
}

static size_t find_matching_open(const char *text, size_t pos, char open, char close) {
    int depth = 1;
    while (pos > 0) {
        pos--;
        char ch = text[pos];

        if (ch == '"') {
            pos--;
            while (pos > 0 && text[pos] != '"') {
                if (text[pos] == '\\' && pos > 0) pos--;
                pos--;
            }
            continue;
        }

        if (ch == close) depth++;
        else if (ch == open) {
            depth--;
            if (depth == 0) return pos;
        }
    }
    return (size_t)-1;
}

size_t clojure_find_sexp_start(const char *text, size_t pos) {
    if (pos == 0) return (size_t)-1;

    while (pos > 0 && (text[pos - 1] == ' ' || text[pos - 1] == '\n' || text[pos - 1] == '\t'))
        pos--;

    if (pos == 0) return (size_t)-1;

    char ch = text[pos - 1];

    if (ch == ')') {
        size_t start = find_matching_open(text, pos - 1, '(', ')');
        if (start == (size_t)-1) return (size_t)-1;
        while (start > 0 && (text[start - 1] == '#' || text[start - 1] == '\'' ||
                             text[start - 1] == '`' || text[start - 1] == '~' ||
                             text[start - 1] == '@'))
            start--;
        return start;
    }

    if (ch == ']') {
        size_t start = find_matching_open(text, pos - 1, '[', ']');
        if (start == (size_t)-1) return (size_t)-1;
        return start;
    }

    if (ch == '}') {
        size_t start = find_matching_open(text, pos - 1, '{', '}');
        if (start == (size_t)-1) return (size_t)-1;
        if (start > 0 && text[start - 1] == '#')
            start--;
        return start;
    }

    if (ch == '"') {
        size_t p = pos - 2;
        while (p > 0) {
            if (text[p] == '"') {
                int backslashes = 0;
                size_t bp = p;
                while (bp > 0 && text[bp - 1] == '\\') {
                    backslashes++;
                    bp--;
                }
                if (backslashes % 2 == 0)
                    return p;
            }
            p--;
        }
        if (text[0] == '"') return 0;
        return (size_t)-1;
    }

    if (clojure_is_symbol_char(ch) || isdigit(ch)) {
        size_t start = pos - 1;
        while (start > 0 && clojure_is_symbol_char(text[start - 1]))
            start--;
        if (start > 0 && text[start - 1] == '@')
            start--;
        return start;
    }

    return (size_t)-1;
}

char *clojure_extract_sexp(const char *text, size_t pos) {
    size_t start = clojure_find_sexp_start(text, pos);
    if (start == (size_t)-1) return NULL;

    while (pos > 0 && (text[pos - 1] == ' ' || text[pos - 1] == '\n' || text[pos - 1] == '\t'))
        pos--;

    size_t len = pos - start;
    return hstrndup(text + start, len);
}
