#include "sci.h"
#include "util.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>
#include <errno.h>
#include <pthread.h>

/* GraalVM isolate headers (generated by native-image --shared) */
#include "graal_isolate.h"
#include "libsci.h"

/* GraalVM isolate handles (single-threaded: one isolate, one thread) */
static graal_isolate_t *isolate = NULL;
static graal_isolatethread_t *thread = NULL;

bool sci_init(void) {
    if (graal_create_isolate(NULL, &isolate, &thread) != 0) {
        fprintf(stderr, "Failed to create GraalVM isolate\n");
        return false;
    }

    int rc = libsci_init(thread);
    if (rc != 0) {
        fprintf(stderr, "sci_init failed\n");
        graal_tear_down_isolate(thread);
        isolate = NULL;
        thread = NULL;
        return false;
    }

    return true;
}

void sci_shutdown(void) {
    if (thread) {
        libsci_shutdown(thread);
        graal_tear_down_isolate(thread);
        thread = NULL;
        isolate = NULL;
    }
}

bool sci_is_ready(void) {
    return thread != NULL;
}

char *sci_eval(const char *expr) {
    if (!thread) return hstrdup("ERROR: SCI not initialized");

    char *result = libsci_eval_string(thread, (char *)expr);
    if (!result) return hstrdup("nil");

    /* Copy the result so caller can free() it normally.
     * GraalVM strings have their own lifecycle. */
    char *copy = hstrdup(result);
    libsci_free_string(thread, result);
    return copy;
}

/* Eval runs on a worker pthread attached to the same GraalVM isolate as
 * the main thread. The isolate is shared, so all side effects — ns
 * registration, def, atom swaps — persist after the eval finishes. The
 * worker serializes against itself via `isolate_mu` so SCI never sees
 * concurrent calls.
 *
 * C-g cancellation is cooperative at the UI layer only: the worker
 * cannot be safely interrupted mid-eval (GraalVM native-image doesn't
 * expose Thread.stop; SCI internals hold non-trivial invariants), so
 * on C-g we detach from the running job, tell the user "Quit", and let
 * the worker finish in the background. Any subsequent sci_eval call
 * blocks at isolate_mu until the previous worker exits. A runaway
 * user loop therefore pins the isolate; this is the accepted tradeoff
 * for keeping editor state across evals. */

static pthread_mutex_t isolate_mu = PTHREAD_MUTEX_INITIALIZER;

typedef struct {
    char *expr;
    char *result;         /* set by worker on completion */
    bool done;
    bool abandoned;       /* main called C-g and walked away */
    pthread_mutex_t m;
    pthread_cond_t cv;
} EvalJob;

static void *eval_worker(void *arg) {
    EvalJob *job = (EvalJob *)arg;

    /* Serialize against any other eval worker still running — SCI is not
     * reentrant, so only one thread may hold the isolate at a time. */
    pthread_mutex_lock(&isolate_mu);

    char *copy = NULL;
    graal_isolatethread_t *t = NULL;
    if (graal_attach_thread(isolate, &t) == 0 && t != NULL) {
        char *r = libsci_eval_string(t, job->expr);
        copy = r ? hstrdup(r) : hstrdup("nil");
        if (r) libsci_free_string(t, r);
        graal_detach_thread(t);
    } else {
        copy = hstrdup("sci_eval error: could not attach worker thread");
    }

    pthread_mutex_unlock(&isolate_mu);

    pthread_mutex_lock(&job->m);
    if (job->abandoned) {
        /* Main has already returned to the user with "Quit". No one is
         * waiting on the cv — clean up the job ourselves. */
        free(copy);
        free(job->expr);
        pthread_mutex_unlock(&job->m);
        pthread_mutex_destroy(&job->m);
        pthread_cond_destroy(&job->cv);
        free(job);
    } else {
        job->result = copy;
        job->done = true;
        pthread_cond_signal(&job->cv);
        pthread_mutex_unlock(&job->m);
    }
    return NULL;
}

SciEvalResult sci_eval_interruptible(const char *expr) {
    SciEvalResult out = { NULL, false };

    if (!thread) {
        out.result = hstrdup("ERROR: SCI not initialized");
        return out;
    }

    EvalJob *job = calloc(1, sizeof(*job));
    if (!job) {
        out.result = sci_eval(expr);
        return out;
    }
    job->expr = hstrdup(expr);
    pthread_mutex_init(&job->m, NULL);
    pthread_cond_init(&job->cv, NULL);

    pthread_t tid;
    if (pthread_create(&tid, NULL, eval_worker, job) != 0) {
        free(job->expr);
        pthread_mutex_destroy(&job->m);
        pthread_cond_destroy(&job->cv);
        free(job);
        out.result = sci_eval(expr);
        return out;
    }
    pthread_detach(tid);

    for (;;) {
        struct pollfd pfd;
        pfd.fd = STDIN_FILENO; pfd.events = POLLIN; pfd.revents = 0;

        int pr = poll(&pfd, 1, 100);  /* 100ms tick for spinner updates */
        if (pr < 0) {
            if (errno == EINTR) continue;
            /* poll failed — abandon job and return an error. */
            pthread_mutex_lock(&job->m);
            job->abandoned = true;
            pthread_mutex_unlock(&job->m);
            out.result = hstrdup("sci_eval error: poll failed while "
                                 "waiting for eval");
            return out;
        }

        if (pfd.revents & POLLIN) {
            unsigned char buf[64];
            ssize_t n = read(STDIN_FILENO, buf, sizeof(buf));
            if (n > 0) {
                bool quit = false;
                for (ssize_t i = 0; i < n; i++) {
                    if (buf[i] == 7 /* C-g */ || buf[i] == 27 /* ESC */) {
                        quit = true; break;
                    }
                }
                if (quit) {
                    pthread_mutex_lock(&job->m);
                    if (job->done) {
                        /* Worker finished between our last check and the
                         * C-g — return the real result, don't lie. */
                        out.result = job->result;
                        pthread_mutex_unlock(&job->m);
                        pthread_mutex_destroy(&job->m);
                        pthread_cond_destroy(&job->cv);
                        free(job->expr);
                        free(job);
                    } else {
                        job->abandoned = true;
                        pthread_mutex_unlock(&job->m);
                        out.cancelled = true;
                        /* Worker owns the job from here; it will free it
                         * when eval returns. */
                    }
                    return out;
                }
                /* Non-quit bytes are swallowed — acceptable since the user
                 * is being told "Evaluating... (C-g to cancel)". */
            }
        }

        pthread_mutex_lock(&job->m);
        if (job->done) {
            out.result = job->result;
            pthread_mutex_unlock(&job->m);
            pthread_mutex_destroy(&job->m);
            pthread_cond_destroy(&job->cv);
            free(job->expr);
            free(job);
            if (!out.result) out.result = hstrdup("nil");
            return out;
        }
        pthread_mutex_unlock(&job->m);
    }
}

long long sci_get_state_version(void) {
    if (!thread) return -1;
    return libsci_get_state_version(thread);
}

char *sci_load_file(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) {
        char err[256];
        snprintf(err, sizeof(err), "ERROR: Could not open %s", path);
        return hstrdup(err);
    }

    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);

    char *content = malloc(len + 1);
    if (!content) {
        fclose(f);
        return hstrdup("ERROR: Out of memory");
    }

    size_t read = fread(content, 1, len, f);
    content[read] = '\0';
    fclose(f);

    char *result = sci_eval(content);
    free(content);
    return result;
}

/* ================================================================
 * Sexp utilities (moved from clojure.c, pure C string parsing)
 * ================================================================ */

bool clojure_is_symbol_char(char ch) {
    if (isalnum(ch)) return true;
    return ch == '-' || ch == '_' || ch == '.' || ch == '/' ||
           ch == '+' || ch == '*' || ch == '!' || ch == '?' ||
           ch == '<' || ch == '>' || ch == '=' || ch == '&' ||
           ch == '%' || ch == '#' || ch == ':' || ch == '\'';
}

static size_t find_matching_open(const char *text, size_t pos, char open, char close) {
    int depth = 1;
    while (pos > 0) {
        pos--;
        char ch = text[pos];

        if (ch == '"') {
            pos--;
            while (pos > 0 && text[pos] != '"') {
                if (text[pos] == '\\' && pos > 0) pos--;
                pos--;
            }
            continue;
        }

        if (ch == close) depth++;
        else if (ch == open) {
            depth--;
            if (depth == 0) return pos;
        }
    }
    return (size_t)-1;
}

size_t clojure_find_sexp_start(const char *text, size_t pos) {
    if (pos == 0) return (size_t)-1;

    while (pos > 0 && (text[pos - 1] == ' ' || text[pos - 1] == '\n' || text[pos - 1] == '\t'))
        pos--;

    if (pos == 0) return (size_t)-1;

    char ch = text[pos - 1];

    if (ch == ')') {
        size_t start = find_matching_open(text, pos - 1, '(', ')');
        if (start == (size_t)-1) return (size_t)-1;
        while (start > 0 && (text[start - 1] == '#' || text[start - 1] == '\'' ||
                             text[start - 1] == '`' || text[start - 1] == '~' ||
                             text[start - 1] == '@'))
            start--;
        return start;
    }

    if (ch == ']') {
        size_t start = find_matching_open(text, pos - 1, '[', ']');
        if (start == (size_t)-1) return (size_t)-1;
        return start;
    }

    if (ch == '}') {
        size_t start = find_matching_open(text, pos - 1, '{', '}');
        if (start == (size_t)-1) return (size_t)-1;
        if (start > 0 && text[start - 1] == '#')
            start--;
        return start;
    }

    if (ch == '"') {
        size_t p = pos - 2;
        while (p > 0) {
            if (text[p] == '"') {
                int backslashes = 0;
                size_t bp = p;
                while (bp > 0 && text[bp - 1] == '\\') {
                    backslashes++;
                    bp--;
                }
                if (backslashes % 2 == 0)
                    return p;
            }
            p--;
        }
        if (text[0] == '"') return 0;
        return (size_t)-1;
    }

    if (clojure_is_symbol_char(ch) || isdigit(ch)) {
        size_t start = pos - 1;
        while (start > 0 && clojure_is_symbol_char(text[start - 1]))
            start--;
        if (start > 0 && text[start - 1] == '@')
            start--;
        return start;
    }

    return (size_t)-1;
}

char *clojure_extract_sexp(const char *text, size_t pos) {
    size_t start = clojure_find_sexp_start(text, pos);
    if (start == (size_t)-1) return NULL;

    while (pos > 0 && (text[pos - 1] == ' ' || text[pos - 1] == '\n' || text[pos - 1] == '\t'))
        pos--;

    size_t len = pos - start;
    return hstrndup(text + start, len);
}
